my_web/core/urls.py
from django.urls import path
from .views import ( ItemDetailView,
    #HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    CheckoutView,
    AddCouponView,
    RequestRefundView,
    sizefilter,
    search,
    items_list,
    reviews,
    contact_form_view,
  
    )
from django.conf.urls.static import static
from django.conf import settings


app_name = 'core'


urlpatterns = [
                  path('', items_list, name='home'),
                  path('checkout/', CheckoutView.as_view(), name='checkout'),
                  path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
                  path('help/',sizefilter, name='help'),
                  path('reviews/',reviews, name='reviews'),
                  path('contact',contact_form_view, name='contact'),
                  path('search/',search, name='search'),
                  path('product/<slug>/', ItemDetailView.as_view(), name='product'),
                  path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
                  path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
                  path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
                  path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
                       name='remove-single-item-from-cart'),
                  path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_web/my_web/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from accounts.views import LoginView, register_page,  RegisterView, guest_register_view, login_page, log_out
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('register/guest', guest_register_view, name='guest_register'),
    path('register', RegisterView.as_view(), name='register'),
    path('login', login_page, name='login'),
    path('logout', log_out , name='logout'),

]

my_web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width = device-width, initial-scale=1.0">
    <title>Leo Sneaker</title>
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--font awsome cdn-->
    <script src="https://kit.fontawesome.com/c6db19dff2.js" crossorigin="anonymous"></script>
    <!--google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Arvo|Gugi|Lato|Roboto|Sofia&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
            $(function() {
                $(".toggle").on("click", function(){
                    if($(".item").hasClass("active")){
                        $(".item").removeClass("active");
                    }
                    else{
                        $(".item").addClass("active");
                    }
                })
            });


    </script>
</head>
<body>
<style>
body {margin:0;font-family:Arial}
.header {
	background: black;
	padding-left: 5em;
}
.button {
	padding-top: 7px;
	overflow: hidden;
	float: right;
}
.button a {
	padding-right: 10px;
	text-decoration: none;
	color: white;
	display: inline-table;
}
.topnav {
  overflow: hidden;
  background-color: #333;
}
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}
.active {
  background-color: #333;
  color: white;
}
.topnav .icon {
  display: none;
}
.dropdown {
  float: left;
  overflow: hidden;
}
.dropdown .dropbtn {
  font-size: 17px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}
.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}
.topnav a:hover, .dropdown:hover .dropbtn {
  background-color: #555;
  color: white;
}
.dropdown-content a:hover {
  background-color: #ddd;
  color: black;
}
.dropdown:hover .dropdown-content {
  display: block;
}
@media screen and (max-width: 600px) {
	.button {
		float: none;
	}
  .topnav a:not(:first-child), .dropdown .dropbtn {
    display: none;
  }
  .topnav a.icon {
    float: right;
    display: block;
  }
}
@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
  .topnav.responsive .dropdown {float: none;}
  .topnav.responsive .dropdown-content {position: relative;}
  .topnav.responsive .dropdown .dropbtn {
    display: block;
    width: 100%;
    text-align: left;
  }
}
#body {
	padding-bottom:60px;
}
#footer {
	position:absolute;
   bottom:0;
   width:100%;
   height:60px;   /* Height of the footer */
}


</style>
<div class="header">
    <a href="{% url 'core:home'%}"><img
            src="https://res.cloudinary.com/dmsqafar4/image/upload/v1589125270/Leo%20sneaker/123_rulx78.png?fbclid=IwAR2eptCs5ryhznGjHn6-Jocqh-sNe1IxZONOx1DM2p-37tB9qvUDKIapG6c"></a>
    <div class="button">
        {% if user.is_authenticated %}
        <a href="{% url 'logout'%}">Đăng Xuất</a>
        {%else%}
        <a href="{%url 'register'%}"><i class="fa fa-user left" aria-hidden="true"></i> Đăng Ký</a>
        <a href="{% url 'login'%}"><i class="fa fa-lock left" aria-hidden="true"></i> Đăng Nhập</a>
        {%endif%}
    </div>
</div>
<div class="topnav" id="myTopnav">
    <a href="{% url 'core:home'%}" class="active">Trang Chủ</a>
    <a href="{% url 'core:help'%}">Tư Vấn Size</a>
    <a href="{% url 'core:reviews'%}">Review Giày</a>
    {% if user.is_authenticated %}
    <a href="{% url 'core:contact'%}">Liên Hệ</a>
    {%endif%}
    <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
    {% load cart_template_tags %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2" style="text-align: center;  ">
            {% if request.user.is_authenticated %}
            <li class="nav-item" style="list-style-type: none ">
                <a href="{% url 'core:order-summary'%}" class="nav-link waves-effect">
                    <span class="badge red z-depth-1 mr-1"
                          style="color: white"> {{ request.user|cart_item_count }} </span>
                    <i class="fas fa-shopping-cart" style="color: white"></i>
                    <span class="clearfix d-none d-sm-inline-block" style="color: white"> Cart </span>
                </a>
            </li>
            {%endif%}
        </div>
    </div>
</div>
<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}


</script>
<div class="mt-1 pt-1">
    {%if messages %}
    {%for message in messages%}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {%endfor%}
    {% endif %}
</div>

{% block reviews %}{% endblock %}
{% block homepage %} {% endblock %}
{% block login %} {% endblock %}
{% block content %} {% endblock %}
{% block product_detail%} {% endblock %}
{% block extra_scripts %} {% endblock extra_scripts %}
{% block extra_head %} {% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
<br><br>
<style>
	.row p{
		color: #999;
		line-height: 24px;
	}
	h2{
		color: #fff;
		font-size: 20px;
	}
	.footer-top{
		background: #111;
		padding: 20px 0;
	}
	.segment-one h2{
		color: #fff;
		font-family: Poppins;
	}
	.segment-one h2:before{
		content: '|';
		color: #c65039;
		padding-right: 10px;
	}
	.segment-two h2{
		color: #fff;
		font-family: Poppins;
		text-transform: uppercase;
	}
	.segment-two h2:before{
		content: '|';
		color: #c65039;
		padding-right: 10px;
	}
	.segment-two ul{
		margin: 0;
		padding: 0;
		list-style-type: none;
	}
	.segment-two ul li{
		border-bottom: 1px solid rgba(255,255,255,0.3);
		line-height: 40px;
	}
	.segment-two ul li a{
		color: #999;
		text-decoration: none;
	}
	.segment-three h2{
		color: #fff;
		font-family: Poppins;
		text-transform: uppercase;
	}
	.segment-three h2:before{
		content: '|';
		color: #c65039;
		padding-right: 10px;
	}
	.segment-three a{
		background: #494848;
		width: 55px;
		height: 55px;
		display: inline-block;
		border-radius: 50%;
	}
	.segment-three a i{
		font-size: 30px;
		color: #fff;
		padding: 12px 12px;
	}
	.segment-four h2{
		color: #fff;
		font-family: Poppins;
		text-transform: uppercase;
	}
	.segment-four h2:before{
		content: '|';
		color: #c65039;
		padding-right: 10px;
	}
	.segment-four form input[type=submit]{
		background: #c65039;
		border: none;
		padding: 3px 15px;
		color: #fff;
		text-transform: uppercase;
	}
	.copyright{
		text-align: center;
		padding-top: 15px;
		background: #000;
		height: 58px;
	}
	/* responsive css */
	@media only screen and (min-width: 768px) and (max-width: 991px){
		.md-mb-30{
			margin-bottom: 30px;
		}
	}
	@media only screen and (max-width: 767px){
		.sm-mb-30{
			margin-bottom: 30px;
		}
		.footer-top{
			padding: 50px 0;
		}
	}


</style>
<footer>
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12 segment-one md-mb-30 sm-mb-30">
                    <h2>LEO Sneaker</h2>
                    <p>Hệ thống cửa hàng giày thể thao thời trang chất lượng. Với phương châm kinh doanh UY TÍN và nâng
                        cao CHẤT LƯỢNG sản phẩm tiêu dùng, cùng kinh nghiệm nhiều năm trong ngành giày dép của ban lãnh
                        đạo, LEO Sneaker đang từng bước trở thành thương hiệu giày thể thao hàng đầu được lựa chọn tại
                        Việt Nam.</p>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12 segment-two md-mb-30 sm-mb-30">
                    <h2>Thông tin</h2>
                    <ul>
                        <li><a href="{% url 'core:home'%}">Trang Chủ</a></li>
                        <li><a href="{% url 'core:help'%}">Tư Vấn Size</a></li>
                        <li><a href="{% url 'core:reviews'%}">Review Giày</a></li>
                        <li><a href="{% url 'core:contact'%}">Liên Hệ</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12 segment-three sm-mb-30 ">
                    <h2>Kết nối với chúng tôi</h2>
                    <p>Theo dõi chúng tôi qua các đường dẫn sau:</p>
                    <a href="https://www.facebook.com/dustin.bo.9"><i class="fa fa-facebook"></i></a>
                    <a href="https://instagram.com/tranducbonlqda?igshid=1wt4is4so3jz4"><i class="fa fa-instagram"></i></a>
                    <a href="https://www.youtube.com/channel/UCqHGORrs8rQx-voDUmdr38w"><i class="fa fa-youtube"></i></a>
                    <a href="https://twitter.com/realdonaldtrump"><i class="fa fa-twitter"></i></a>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12 segment-four sm-mb-30">
                    <h2>Đăng ký nhận Email</h2>
                    <p>Đăng ký ngay để nhận được album mới, các chương trình khuyến mãi mới.</p>
                    <div class="header">
                        <div class="button">
                            {% if user.is_authenticated %}
                            <a href="{% url 'logout'%}">Đăng Xuất</a>
                            {%else%}
                            <a href="{%url 'register'%}"><i class="fa fa-user left" aria-hidden="true"></i> Đăng Ký</a>
                            <a href="{% url 'login'%}"><i class="fa fa-lock left" aria-hidden="true"></i> Đăng Nhập</a>
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright"><p>2020 © <strong>LEO Sneaker</strong>. All rights reserved. <a href="#" target="_blank"
                                                                                           style="color: #999; text-decoration: none;">DEVELOPED
        BY Team2 - 43K21</a></p></div>
</footer>
</html>

my_web/templates/contact.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block login %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

/* Style inputs */
input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=email], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}


input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}


/* Create two columns that float next to eachother */
.column {
  float: left;
  width: 50%;
  margin-top: 6px;
  padding: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    margin-top: 0;
  }
}
.map-responsive{
    overflow:hidden;
    padding-bottom: 90%;
    position:relative;
    height:0;
}
.map-responsive iframe{
    left:0;
    top:0;
    height:100%;
    width:100%;
    position:absolute;
}

button{
    float: right;
    width: 120px;
    height: 50px;
    </style>
</head>
<body>

<div class="container" style="border-radius: 5px;  background-color: #f2f2f2;  padding: 10px;">
    <div style="text-align:center">
        <h1 style="color: black"><strong>Liên hệ</strong></h1>
        <h2 style="color: black">Nếu có bất kì thắc mắc gì cần được giải đáp, Quý khách có thể để lại lời nhắn:</h2>
    </div>
    <div class="row">
        <div class="column">
            <div class="map-responsive">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3834.3304957881624!2d108.23762171433641!3d16.04833064426165!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142172023b9d4e1%3A0x4f62282c99b1c906!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBLaW5oIHThur8gLSDEkOG6oWkgaOG7jWMgxJDDoCBO4bq1bmc!5e0!3m2!1svi!2s!4v1589099087232!5m2!1svi!2s"
                        width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""
                        aria-hidden="false" tabindex="0"></iframe>
            </div>
        </div>
        <div class="column">
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form|crispy}}
            <button type="submit" class="btn btn-success btn-md my-0 p">Send</button>
        </form>
        </div>
    </div>
</div>

</body>


{%endblock%}

my_web/templates/home.html
{% extends 'base.html'%}
{% block homepage %}

<style>
    .carousel-inner{
    width: 100%;
    margin-left: 5px;
    margin-right: 15px;
    }
    .list-product-title{
    width: 100%;
    text-transform: uppercase;
    margin: 0px 5px;
    }
    .list-product-subtitle{
    width: 100%;
    margin: 0px 5px;
    }
    .card-product{
    margin: 0px 5px;
    overflow : hidden;
    }






</style>
<style>
tr{
    height: 30px;
}
/* Reset Select */
select {
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  appearance: none;
  outline: 0;
  box-shadow: none;
  border: 0 !important;
  background: #ebedef;
  background-image: none;
}
/* Remove IE arrow */
select::-ms-expand {
  display: none;
}
/* Custom Select */
.select {
  position: relative;
  display: flex;
  width: 20em;
  height: 3em;
  line-height: 3;
  background: #ebedef;
  overflow: hidden;
  border-radius: .25em;
}
select {
  flex: 1;
  padding: 0 1em;
  color: #000000;
  cursor: pointer;
  font-size: 1em;
}

/* Arrow */
.select::after {
  content: '\25BC';
  position: absolute;
  top: 0;
  right: 0;
  padding: 0 1em;
  background: #838e95;
  cursor: pointer;
  pointer-events: none;
  -webkit-transition: .25s all ease;
  -o-transition: .25s all ease;
  transition: .25s all ease;
}
/* Transition */
.select:hover::after {
  color: #fff;
}

.active-pink-2 input.form-control[type=text]:focus:not([readonly]) {
              border-bottom: 1px solid #f48fb1;
              box-shadow: 0 1px 0 0 #f48fb1;
            }





</style>

<!-- slide--->
<!--<div class="container ">
    <div id="carouselExampleIndicators" class="carousel slide mt-3" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="http://via.placeholder.com/1920x700" class="d-block w-100" alt="First Slide">
            </div>
            <div class="carousel-item">
                <img src="http://via.placeholder.com/1920x700" class="d-block w-100" alt="Second Slide">
            </div>
            <div class="carousel-item">
                <img src="http://via.placeholder.com/1900x700" class="d-block w-100" alt="Third Slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div> -->
<!-- end slide -->
{% load widget_tweaks %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
    <div class="col-md-3"></div>
    <div class="col-md-3" >
        <form method="get" class="border p-3">
            <div class="mb-1">
                <strong><label for="">Tên sản phẩm:</label></strong>
                {% render_field form.title class="form-control" %}
            </div>
            <div class="mb-2">
                <strong><label for="">Size:</label></strong>
                {% render_field form.size class="form-control" %}
            </div>
            <hr class="mb-3">
            <div class="form-group" style="text-align:center">
                    <button type="submit" class="btn btn-danger" value="Submit" id="submit">Search...
                    </button>
            </div>
        </form>
    </div>
</div>

<div class="container mt-5 text-center">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1 class="list-product-title" style="color: black">All product</h1>
            <div class="list-product-subtitle">
                <p style="color: black">List product description</p>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
    <div class="container mt-3">
        <div class="product-group">
            <div class="row">
                {%for item in items %}
                <div class="col-md-3 col-sm-6 col-12 mt-3">
                    <div class="card card-product" style="width: 270px;">
                        <img src="{{item.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h4>
                                <strong>
                                    {{item.title}}
                                </strong>
                            </h4>
                            <h6>

                                <strong> Size: </strong>{{item.size_verbose}}

                            </h6>
                            <h6>
                                {% if item.discount_price%}
                                <span class="text-right"></span>{{item.discount_price}} VND
                                {% else %}
                                <span class="text-right"></span>{{item.price}} VND
                                {% endif %}
                            </h6>
                            <a href="{{item.get_absolute_url}}" class="btn btn-primary btn-md my-0 p">Go to detail
                            </a>
                            <br>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</div>

{% if is_paginated %}
<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">
        {%if page_obj.has_previous %}
        <!--Arrow left-->
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {%endif%}


        <li class="page-item active">
            <a class="page-link" href="page={{page_obj.page_number}}">{{page_obj.page_number}}
                <span class="sr-only">(current)</span>
            </a>
        </li>
        {%if page.obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {%endif%}
    </ul>
</nav>
{%endif%}
<!--show produc-->
<!--end show produc-->
{% endblock %}

my_web/templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">{{ order_item.get_final_price }} VND</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-{{ order.coupon.amount }} VND</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (VND)</span>
        <strong>{{ order.get_total }} VND</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

my_web/templates/order_summary.html
{% extends 'base.html'%}
{%block content%}
<main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving {{ order_item.get_amount_saved }} VND</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{%endblock%}

my_web/templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock %}